version: '3.8'

services:
# (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: reporting_db_container
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: reporting_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# (Redis)
  redis:
    image: redis:alpine
    container_name: reporting_redis_container
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: