version: '3.8'

services:
# (PostgreSQL)
  postgres:
    image: postgres:15-alpine
    container_name: reporting_db_container
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: reporting_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# (Redis)
  redis:
    image: redis:alpine
    container_name: reporting_redis_container
    restart: always
    ports:
      - "6379:6379"
# (Prisma Studio) to access the database and manage data visually
  prisma-studio:
    image: node:22-slim
    container_name: prisma_studio_container
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "apt-get update -y && apt-get install -y openssl && npx prisma studio --config=./prisma/prisma.config.ts --url="postgresql://user_admin:password123@postgres:5432/reporting_db?schema=public" --browser none --port 5555"
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres

volumes:
  postgres_data: